apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  generation: 8
  labels:
    run: ghost
  name: ghost
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      run: ghost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ghost
    spec:
      containers:
      - image: ghost
        imagePullPolicy: IfNotPresent  
        name: ghost
        ports:
        - containerPort: 2368
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
